# Generated by Django 4.1.6 on 2023-03-03 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abracadabra_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(max_length=255)),
                ('subscription_plan_id', models.CharField(max_length=255)),
                ('subscription_plan_price', models.CharField(max_length=255)),
                ('subscription_plan_price_id', models.CharField(max_length=255)),
                ('subscription_purchase_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_status', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
