# Generated by Django 4.1.6 on 2023-03-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abracadabra_app', '0002_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='user_id',
            new_name='user',
        ),
    ]
